name: squilder
description: Type-safe builder of SQL strings (forked from astashov)
version: 0.0.2
homepage: https://github.com/ggof/squilder

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  postgres:

dev_dependencies:
  test:
  test_coverage:
